import json
import logging
from typing import List
from langchain_core.messages import BaseMessage
from agents.state import AgentState
from llm.litellm_router.router import llm_router

logger = logging.getLogger(__name__)

# Core list of valid worker routing destinations
VALID_WORKERS = ["Coder", "Researcher", "MemoryWorker", "FINISH"]

SUPERVISOR_SYSTEM_PROMPT = (
    "You are the Core Supervisor for a high-performance, JARVIS-class AI Operating System.\n"
    "Your objective is to orchestrate a pool of specialized worker agents to fulfill the user's request.\n\n"
    "Available Workers:\n"
    "- Coder: Handles backend programming, code structural execution, algorithms, and technical compilation.\n"
    "- Researcher: Conducts high-level conceptual analysis, explanation, and systematic knowledge retrieval.\n"
    "- MemoryWorker: Handles storing, updating, or fetching historical facts from the persistent vector cortex.\n\n"
    "Analyze the conversation history and strategically select the next logical worker to deploy, or choose FINISH if the task is completely answered.\n"
    "You MUST respond ONLY with a raw JSON object matching this exact layout:\n"
    "{\n"
    '  "next_node": "Coder" | "Researcher" | "MemoryWorker" | "FINISH"\n'
    "}\n"
    "Do not output markdown code blocks or additional conversational text outside the raw JSON object."
)

def convert_messages_to_router_format(messages: List[BaseMessage]) -> List[dict]:
    """Maps LangChain core structural messages into standard LiteLLM role-content payloads."""
    router_messages = []
    for msg in messages:
        if msg.type == "human":
            role = "user"
        elif msg.type == "ai":
            role = "assistant"
        else:
            role = "system"
        router_messages.append({"role": role, "content": msg.content})
    return router_messages

async def supervisor_node(state: AgentState) -> dict:
    """
    Asynchronous cognitive supervisor execution block.
    Evaluates chat history logs and shifts operational control to worker systems.
    """
    logger.info("🧠 Supervisor orchestrator calculating next logical system vector...")
    
    # Initialize complete conversational context payload
    payload = [{"role": "system", "content": SUPERVISOR_SYSTEM_PROMPT}]
    payload.extend(convert_messages_to_router_format(state["messages"]))
    
    # Run payload routing through our high-availability Phase 6 LiteLLM framework
    response = await llm_router.generate_reply(
        messages=payload,
        temperature=0.0  # Lock temperature to ensure deterministic routing decisions
    )
    
    if not response.get("success"):
        logger.error(f"Supervisor routing breakdown: {response.get('error')}")
        return {"next_node": "FINISH"}
        
    raw_content = response.get("content", "").strip()
    
    # Sanitize markdown block wrappers if generated by underlying LLM provider tiers
    if raw_content.startswith("```json"):
        raw_content = raw_content.split("```json")[1].split("```")[0].strip()
    elif raw_content.startswith("```"):
        raw_content = raw_content.split("```")[1].split("```")[0].strip()

    try:
        decision = json.loads(raw_content)
        next_destination = decision.get("next_node", "FINISH")
        
        if next_destination not in VALID_WORKERS:
            next_destination = "FINISH"
            
        logger.info(f"🔀 Supervisor routing operational thread control to: [{next_destination}]")
        return {"next_node": next_destination}
        
    except Exception as e:
        logger.error(f"Failed to parse routing execution matrix: {e}. Raw content payload: {raw_content}")
        return {"next_node": "FINISH"}